packages:
  - web
  - admin
  - mobile
  - game
  - desktop
  - packages/*

allowBuilds:
  '@firebase/util': false
  protobufjs: false
  electron: true
  electron-winstaller: false

overrides:
  firebase: 12.16.0

nodeLinker: hoisted
