ALTER TABLE users ALTER COLUMN bio DROP DEFAULT;
ALTER TABLE users DROP COLUMN IF EXISTS following_count;
ALTER TABLE users DROP COLUMN IF EXISTS follower_count;
ALTER TABLE users DROP COLUMN IF EXISTS vip_end_time;
ALTER TABLE users DROP COLUMN IF EXISTS vip_used;
ALTER TABLE users DROP COLUMN IF EXISTS ken;
ALTER TABLE users DROP COLUMN IF EXISTS gender;
