ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(10) NOT NULL DEFAULT 'male';
ALTER TABLE users ADD COLUMN IF NOT EXISTS ken INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS vip_used VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS vip_end_time TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS follower_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS following_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE users ALTER COLUMN bio SET DEFAULT 'hello ola!!!';
UPDATE users SET bio = 'hello ola!!!' WHERE bio IS NULL OR bio = '';
