export const STORY_ICON_ASSET_NAMES = [
  'chevronLeft',
  'chevronRight',
  'list',
  'formatSize',
  'importExport',
  'visibility',
  'menuBook',
  'article',
  'chatBubble',
  'schedule',
  'done',
  'inkPen',
  'bookmark',
  'autoAwesome',
  'lightMode',
  'darkMode',
  'palette',
  'textFields',
  'formatLineSpacing',
  'priorityHigh',
  'arrowDropDown',
  'book',
  'emojiEvents',
  'libraryBooks',
  'filterAlt',
  'search',
] as const;

export type StoryIconName = (typeof STORY_ICON_ASSET_NAMES)[number];
