// Code generated by server/cmd/thirteengen; DO NOT EDIT.

export const GAME_ID = "thirteen";
export const TURN_SECONDS = 30;
export const HAND_SIZE = 13;
export const DECK_SIZE = 52;
export const RANK_TWO = 12;
export const THREE_OF_SPADES = 0;

export const COMBO_KINDS = [
  "single",
  "pair",
  "triple",
  "quad",
  "straight",
  "doubleRun",
] as const;
export type ComboKind = (typeof COMBO_KINDS)[number];

export const INSTANT_WINS = [
  "fourTwos",
  "dragonStraight",
  "fourPairRun",
  "sixPairs",
] as const;
export type InstantWinKind = (typeof INSTANT_WINS)[number];

export const STEP_KINDS = [
  "deal",
  "play",
  "pass",
  "clear",
  "finish",
  "instant",
] as const;
export type StepKind = (typeof STEP_KINDS)[number];
