/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.tsx', './src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        'ola-primary': 'var(--ola-color-primary, #7cb342)',
        'ola-primary-dark': 'var(--ola-color-primary-dark, #558b2f)',
        'ola-primary-darker': 'var(--ola-color-primary-darker, #33691e)',
        'ola-primary-light': 'var(--ola-color-primary-light, #f1f8e9)',
        'ola-button': 'var(--ola-color-button, #9ccc65)',
        'ola-accent': '#ff4081',
        'ola-accent-dark': '#f50057',
        'ola-error': '#e34545',
        'ola-surface': '#f3f3f3',
        'ola-border-strong': '#d5d5d5',
        'ola-ink': 'rgba(0,0,0,0.87)',
        'ola-ink-soft': 'rgba(0,0,0,0.54)',
        'ola-ink-faint': 'rgba(0,0,0,0.38)',
        'ola-ink-hint': 'rgba(0,0,0,0.26)',
        'ola-divider': 'rgba(0,0,0,0.12)',
        'ola-warning': '#ff9800',
      },
      fontSize: {
        xs: ['var(--ola-font-xs, 10.5px)', { lineHeight: 'var(--ola-leading-xs, 14px)' }],
        sm: ['var(--ola-font-sm, 12.25px)', { lineHeight: 'var(--ola-leading-sm, 17.5px)' }],
        base: ['var(--ola-font-base, 14px)', { lineHeight: 'var(--ola-leading-base, 21px)' }],
        lg: ['var(--ola-font-lg, 15.75px)', { lineHeight: 'var(--ola-leading-lg, 24.5px)' }],
        xl: ['var(--ola-font-xl, 17.5px)', { lineHeight: 'var(--ola-leading-xl, 24.5px)' }],
        '2xl': ['var(--ola-font-2xl, 21px)', { lineHeight: 'var(--ola-leading-2xl, 28px)' }],
        '3xl': ['var(--ola-font-3xl, 26.25px)', { lineHeight: 'var(--ola-leading-3xl, 31.5px)' }],
        '4xl': ['var(--ola-font-4xl, 31.5px)', { lineHeight: 'var(--ola-leading-4xl, 35px)' }],
        '5xl': ['var(--ola-font-5xl, 42px)', { lineHeight: 'var(--ola-leading-5xl, 42px)' }],
        '6xl': ['var(--ola-font-6xl, 52.5px)', { lineHeight: 'var(--ola-leading-6xl, 52.5px)' }],
        '7xl': ['var(--ola-font-7xl, 63px)', { lineHeight: 'var(--ola-leading-7xl, 63px)' }],
        '8xl': ['var(--ola-font-8xl, 84px)', { lineHeight: 'var(--ola-leading-8xl, 84px)' }],
        '9xl': ['var(--ola-font-9xl, 112px)', { lineHeight: 'var(--ola-leading-9xl, 112px)' }],
      },
    },
  },
  plugins: [],
};
