export const API_PATH = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    refresh: '/auth/refresh',
    changePassword: '/auth/change-password',
    sendVerifyEmail: '/auth/verify-email/send',
    confirmVerifyEmail: '/auth/verify-email/confirm',
    logout: '/auth/logout',
  },
  rooms: {
    browse: '/rooms',
    detail: (id: string) => `/rooms/${id}`,
    join: (id: string) => `/rooms/${id}/join`,
    members: (id: string) => `/rooms/${id}/members`,
    messages: (id: string) => `/rooms/${id}/messages`,
    messagesImages: (id: string) => `/rooms/${id}/messages/images`,
    message: (id: string, messageId: string) => `/rooms/${id}/messages/${messageId}`,
    messageReactions: (id: string, messageId: string) => `/rooms/${id}/messages/${messageId}/reactions`,
  },
  adminRooms: {
    base: '/admin/rooms',
    detail: (id: string) => `/admin/rooms/${id}`,
  },
  userSettings: '/user-settings',
  appSettings: {
    topup: '/settings/topup',
  },
  user: {
    me: '/user/me',
    search: '/user/search',
    upload: '/user/upload',
    presence: '/user/presence',
    detail: (id: string) => `/user/${id}`,
    kiss: (id: string) => `/user/${id}/kiss`,
    follow: (id: string) => `/user/${id}/follow`,
    followers: (id: string) => `/user/${id}/followers`,
    following: (id: string) => `/user/${id}/following`,
    myVisitors: '/user/me/visitors',
  },
  notifications: {
    base: '/notifications',
    unread: '/notifications/unread-count',
    readAll: '/notifications/read-all',
  },
  relationships: {
    request: '/relationships/request',
    respond: (id: string) => `/relationships/${id}/respond`,
    cancel: (id: string) => `/relationships/${id}/cancel`,
    unfriend: (id: string) => `/relationships/${id}/unfriend`,
    block: '/relationships/block',
    unblock: (id: string) => `/relationships/${id}/unblock`,
    pending: '/relationships/pending',
    sent: '/relationships/sent',
    friends: '/relationships/friends',
    blocked: '/relationships/blocked',
  },
  me: {
    base: '/me',
    mine: '/me/mine',
    photos: '/me/photos',
    liked: '/me/liked',
    users: (userId: string) => `/me/users/${userId}`,
    detail: (id: string) => `/me/${id}`,
    images: '/me/images',
    pin: (id: string) => `/me/${id}/pin`,
    react: (id: string) => `/me/${id}/react`,
    likers: (id: string) => `/me/${id}/likers`,
    comments: (id: string) => `/me/${id}/comments`,
    comment: (id: string, commentId: string) => `/me/${id}/comments/${commentId}`,
    commentLike: (id: string, commentId: string) => `/me/${id}/comments/${commentId}/like`,
    commentLikers: (id: string, commentId: string) =>
      `/me/${id}/comments/${commentId}/likers`,
    notifications: '/me/notifications',
    notificationsUnread: '/me/notifications/unread-count',
    notificationsReadAll: '/me/notifications/read-all',
  },
  clans: {
    base: '/clans',
    checkName: '/clans/check-name',
    mine: '/clans/mine',
    byHandle: (handle: string) => `/clans/by-handle/${handle}`,
    detail: (id: string) => `/clans/${id}`,
    avatar: (id: string) => `/clans/${id}/avatar`,
    cover: (id: string) => `/clans/${id}/cover`,
    join: (id: string) => `/clans/${id}/join`,
    members: (id: string) => `/clans/${id}/members`,
    roles: (id: string) => `/clans/${id}/roles`,
    role: (id: string, role: string) => `/clans/${id}/roles/${role}`,
    verify: (id: string) => `/clans/${id}/verify`,
    bans: (id: string) => `/clans/${id}/bans`,
    ban: (id: string, userId: string) => `/clans/${id}/bans/${userId}`,
    posts: (id: string) => `/clans/${id}/me`,
    pin: (id: string) => `/clans/${id}/pin`,
    post: (id: string, postId: string) => `/clans/${id}/me/${postId}`,
    postsByUser: (id: string, userId: string) => `/clans/${id}/me/by-user/${userId}`,
  },
  conversations: {
    base: '/conversations',
    directCheck: '/conversations/direct/check',
    direct: '/conversations/direct',
    group: '/conversations/group',
    detail: (id: string) => `/conversations/${id}`,
    read: (id: string) => `/conversations/${id}/read`,
    hide: (id: string) => `/conversations/${id}/hide`,
    unhide: (id: string) => `/conversations/${id}/unhide`,
    mute: (id: string) => `/conversations/${id}/mute`,
    unmute: (id: string) => `/conversations/${id}/unmute`,
    typing: '/conversations/typing',
  },
  vip: {
    store: '/vip/store',
    userStore: (userId: string) => `/vip/users/${userId}/store`,
    storePrivacy: '/vip/store/privacy',
    iconCatalog: '/vip/icons/catalog',
    buy: '/vip/buy',
    gift: '/vip/gift',
    packages: '/vip/packages',
    buyPackage: (id: string) => `/vip/packages/${id}/buy`,
    giftPackage: (id: string) => `/vip/packages/${id}/gift`,
    iconUse: (id: string) => `/vip/icons/${id}/use`,
    iconLock: (id: string) => `/vip/icons/${id}/lock`,
    iconUnlock: (id: string) => `/vip/icons/${id}/unlock`,
    iconTransfer: (id: string) => `/vip/icons/${id}/transfer`,
    iconDelete: (id: string) => `/vip/icons/${id}`,
    iconBatchDelete: '/vip/icons/batch-delete',
    history: '/vip/history',
    transfers: '/vip/transfers',
  },
  egg: {
    packs: '/egg/packs',
    gifts: (id: string) => `/egg/packs/${id}/gifts`,
    draw: (id: string) => `/egg/packs/${id}/draws`,
    draws: '/egg/draws',
  },
  wheel: {
    config: '/wheel',
    spins: '/wheel/spins',
  },
  miniGame: {
    list: '/mini-games',
  },
  ken: {
    transfer: '/ken/transfer',
    transactions: '/ken/transactions',
  },
  kenTreasure: {
    open: (id: string) => `/ken/chests/${id}/open`,
  },
  marriage: {
    status: '/marriage',
    divorce: '/marriage/divorce',
    proposals: '/marriage/proposals',
    proposal: (id: string) => `/marriage/proposals/${id}`,
    proposalAccept: (id: string) => `/marriage/proposals/${id}/accept`,
    proposalReject: (id: string) => `/marriage/proposals/${id}/reject`,
    diary: '/marriage/diary',
    diaryDetail: (id: string) => `/marriage/diary/${id}`,
  },
  pen: {
    shots: '/pen/shots',
    mine: '/pen/mine',
    history: '/pen/history',
    historyAll: '/pen/history/all',
    leaderboard: '/pen/leaderboard',
    catch: (id: string) => `/pen/shots/${id}/catch`,
    cancel: (id: string) => `/pen/shots/${id}/cancel`,
  },
  messages: {
    base: '/messages',
    direct: '/messages/direct',
    images: '/messages/images',
    audio: '/messages/audio',
    byConversation: (conversationId: string) => `/messages/${conversationId}`,
    detail: (conversationId: string, messageId: string) =>
      `/messages/${conversationId}/${messageId}`,
    reactions: (conversationId: string, messageId: string) =>
      `/messages/${conversationId}/${messageId}/reactions`,
  },
} as const;
