export { vipIconUrl, parseVipTypeId } from '@lib';

export interface VipCatalogEntry {
  id: number;
  name: string;
}

const VIP_NAMES = [
  'Nhan Vien Ola Cap 1',
  'Nhan Vien Ola Cap 2',
  'Nhan Vien Ola Cap 3',
  'Zakumi Đại Đế',
  'VIP Iphone 5s',
  'Tử Thần',
  'Emperor Fuleco',
  'Empress Fuleco',
  'Khỉ Đột',
  'Zakumi Gao Cam',
  'Cool Boy',
  'Tí Papa',
  'Zakumi Gao Đen',
  'Dũng Sĩ Huyền Thoại Hercules (Hec-Quyn)',
  'Vương Hậu',
  'Nguyên Soái',
  'Đô-rê-mi',
  'Cục... Cưng',
  'Thiết Phiến Công Chúa',
  'Xê-ko',
  'Xu-ka',
  'Zakumi Đại Ca',
  'Tiểu Thư',
  'Trái Tim Ngục Tù',
  'Zakumi Gao Đội Trưởng',
  'Trái Tim Tự Do',
  'Tí Cận',
  'Zakumi Gao Trắng',
  'Garu',
  'Yêu Nhền Nhện',
  'Zakumi Thiên Thần',
  'Zakumi Tam Ca',
  'Yahoo',
  'Offline',
  'Chai-en',
  'Rắn Vàng Quý Tỵ',
  'Cánh Cụt Kute',
  'Zakumi Út',
  'Vô Ảnh Tử Thần',
  'Trứng Apple (nở ra iPhone5s hoặc VIP Độc)',
  'Lão Gà-mên',
  'Cậu Bé Đại Dương',
  'Tí Điệu',
  'Đại Hiệp Phu Nhân',
  'Zakumi Gao Vàng',
  'Zakumi Gao Xanh',
  'Đô-rê-mon',
  'Zakumi Võ Sư',
  'Pucca',
  'Zakumi Ác Thần',
  'Vua Của Các Vị Thần Zeus',
  'Zakumi Omar',
  'Tiên Đế',
  'Thiếu Gia',
  'Zakumi Idol (Đại Gia)',
  'Ngựa Bay Tí Hon',
  'Hoàng Hậu',
  'Đại Hiệp',
  'Hắc Miu',
  'Zakumi Hoàng Tử Arap',
  'Zakumi Thống Lĩnh',
  'Đức Vua',
  'Nô-bi-ta',
  'Zakumi Nhị Ca',
  'Tí Đô (Lực Sĩ)',
  'Thần Khôn Ngoan Hermes',
  'Hoàng Tử',
  'Đắc Kỷ',
  'Quận Chúa',
  'Hồ Ly Tinh',
  'Ghost Rider',
  'Công Chúa',
  'Chó Puppy',
  'Phó Tướng Phu Nhân',
  'Phó Tướng',
  'Tí Lười',
  'Tí Cô Nương',
  'Heo Hồng Boorin',
  'Chiến Binh Bất Tử Achilles',
  'Quân Sư Phu Nhân',
  'Nữ Thần Toàn Năng Athena',
  'Quân Sư',
  'Zakumi Tiên Tri',
  'Zakumi Sắt',
  'Vương Thần Địa Ngục Hades',
  'Conan',
  'InuYasha',
  'Sesumarou',
  'Kagome',
  'Ran Mori',
  'Zakumi Vương Tử',
  'Diêm Đế',
  'Diêm Thiếu Gia',
  'Ma Kute',
  'Nữ Thần Tình Yêu Aphrodite',
  'Thần Mặt Trời Apollo',
  'Thần Chiến Tranh Ares',
  'Nữ Thần Hôn Nhân Hera',
  'Nữ Thần Săn Bắn Artemis',
  'Vương Thần Biển Cả Poseidon',
  'Bạch Dương (21.3-19.4)',
  'Kim Ngưu (20.4-20.5)',
  'Song Tử (21.5-21.6)',
  'Cự Giải (22.6-22.7)',
  'Sư Tử (23.7-22.8)',
  'Xử Nữ (23.8-22.9)',
  'Thiên Bình (23.9-23.10)',
  'Hổ Cáp (24.10-22.11)',
  'Nhân Mã (23.11-21.12)',
  'Ma Kết (22.12-19.1)',
  'Bảo Bình (20.1-18.2)',
  'Song Ngư (19.2-20.3)',
  'Thủy Long',
  'Địa Long',
  'Hỏa Long',
  'Linh Điêu',
  'Thần Điêu',
  'Phượng Hoàng Trí Tuệ',
  'Phượng Hoàng Toàn Năng',
  'Phượng Hoàng Sắc Đẹp',
];

export const VIP_CATALOG: VipCatalogEntry[] = VIP_NAMES.map((name, index) => ({
  id: index + 1,
  name,
}));

export function vipById(id: number): VipCatalogEntry | undefined {
  return VIP_CATALOG[id - 1];
}

export function vipName(id: number): string {
  return vipById(id)?.name ?? `VIP ${id}`;
}
