// Command thirteengen exports server-authoritative Tien Len constants and parity fixtures.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	thirteen "ola-chat-server/internal/game/games/thirteen"
)

func main() {
	constantsPath := flag.String("constants", "", "output path for generated TypeScript constants")
	parityPath := flag.String("parity", "", "output path for the JSON parity fixture")
	flag.Parse()
	if *constantsPath == "" || *parityPath == "" {
		fmt.Fprintln(os.Stderr, "both -constants and -parity are required")
		os.Exit(2)
	}

	if err := writeFile(*constantsPath, RenderConstants(thirteen.ExportClientConfig())); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fixture, err := json.MarshalIndent(thirteen.ExportParityFixture(), "", "  ")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fixture = append(fixture, '\n')
	if err := writeFile(*parityPath, fixture); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func RenderConstants(config thirteen.ClientConfig) []byte {
	var out bytes.Buffer
	out.WriteString("// Code generated by server/cmd/thirteengen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "export const GAME_ID = %q;\n", config.GameID)
	fmt.Fprintf(&out, "export const TURN_SECONDS = %d;\n", config.TurnSeconds)
	fmt.Fprintf(&out, "export const HAND_SIZE = %d;\n", config.HandSize)
	fmt.Fprintf(&out, "export const DECK_SIZE = %d;\n", config.DeckSize)
	fmt.Fprintf(&out, "export const RANK_TWO = %d;\n", config.RankTwo)
	fmt.Fprintf(&out, "export const THREE_OF_SPADES = %d;\n\n", config.ThreeOfSpades)

	writeList := func(name string, values []string) {
		fmt.Fprintf(&out, "export const %s = [\n", name)
		for _, value := range values {
			fmt.Fprintf(&out, "  %q,\n", value)
		}
		out.WriteString("] as const;\n")
	}
	writeList("COMBO_KINDS", config.ComboKinds)
	out.WriteString("export type ComboKind = (typeof COMBO_KINDS)[number];\n\n")
	writeList("INSTANT_WINS", config.InstantWins)
	out.WriteString("export type InstantWinKind = (typeof INSTANT_WINS)[number];\n\n")
	writeList("STEP_KINDS", config.StepKinds)
	out.WriteString("export type StepKind = (typeof STEP_KINDS)[number];\n")
	return out.Bytes()
}

func writeFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
