import type { MePost } from './types';

export const ME_POSTS: MePost[] = [
  {
    id: 'p1',
    author: 'linhchi92',
    color: '#7cb342',
    time: '5 phút trước',
    content: 'Hôm nay trời đẹp quá ☀️ Đi cà phê với @tuananh @maiphuong nào! #ola',
    image: null,
    checkIn: 'The Coffee House · 86-88 Cao Thắng, Q3',
    comments: 12,
    likes: 34,
    likers: ['#ef5350', '#5c6bc0', '#26a69a'],
    liked: false,
    disliked: false,
    mention: false,
  },
  {
    id: 'p5',
    author: 'linhchi92',
    color: '#7cb342',
    time: '10 phút trước',
    content: 'Album chuyến đi Đà Lạt 📷 #travel @quanghuy',
    image: null,
    photos: [
      'https://picsum.photos/seed/ola1/400/400',
      'https://picsum.photos/seed/ola2/400/400',
      'https://picsum.photos/seed/ola3/400/400',
      'https://picsum.photos/seed/ola4/400/400',
      'https://picsum.photos/seed/ola5/400/400',
      'https://picsum.photos/seed/ola6/400/400',
      'https://picsum.photos/seed/ola7/400/400',
    ],
    comments: 5,
    likes: 18,
    likers: ['#4dd0e1', '#7e57c2'],
    liked: false,
    disliked: false,
    mention: false,
  },
  {
    id: 'p2',
    author: 'tuananh',
    color: '#5d4037',
    time: '20 phút trước',
    content: '@me ơi cuối tuần này đi đá bóng không? ⚽',
    image: null,
    comments: 4,
    likes: 8,
    likers: ['#ec407a', '#ffa726'],
    liked: false,
    disliked: false,
    mention: true,
  },
  {
    id: 'p3',
    author: 'maiphuong',
    color: '#6d4c41',
    time: '1 giờ trước',
    content: 'Vừa nghe xong album mới, hay xuất sắc 🎧🎶',
    image: '🎵',
    comments: 7,
    likes: 21,
    likers: ['#4dd0e1', '#7e57c2', '#9ccc65'],
    liked: true,
    disliked: false,
    mention: false,
  },
  {
    id: 'p4',
    author: 'quanghuy',
    color: '#4dd0e1',
    time: 'hôm qua',
    content: 'Chia sẻ chút động lực đầu tuần cho mọi người nhé 💪 Cố lên!',
    image: null,
    comments: 2,
    likes: 15,
    likers: ['#7cb342', '#ef5350'],
    liked: false,
    disliked: false,
    mention: false,
  },
];
