// Command xiangqigen exports server-authoritative Xiangqi constants and parity fixtures.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	xiangqi "ola-chat-server/internal/game/games/xiangqi"
)

func main() {
	constantsPath := flag.String("constants", "", "output path for generated TypeScript constants")
	parityPath := flag.String("parity", "", "output path for the JSON parity fixture")
	flag.Parse()
	if *constantsPath == "" || *parityPath == "" {
		fmt.Fprintln(os.Stderr, "both -constants and -parity are required")
		os.Exit(2)
	}

	if err := writeFile(*constantsPath, RenderConstants(xiangqi.ExportClientConfig())); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fixture, err := json.MarshalIndent(xiangqi.ExportParityFixture(), "", "  ")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fixture = append(fixture, '\n')
	if err := writeFile(*parityPath, fixture); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func RenderConstants(config xiangqi.ClientConfig) []byte {
	var out bytes.Buffer
	out.WriteString("// Code generated by server/cmd/xiangqigen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "export const GAME_ID = %q;\n", config.GameID)
	fmt.Fprintf(&out, "export const TURN_SECONDS = %d;\n", config.TurnSeconds)
	fmt.Fprintf(&out, "export const BOARD_WIDTH = %d;\n", config.BoardWidth)
	fmt.Fprintf(&out, "export const BOARD_HEIGHT = %d;\n", config.BoardHeight)
	fmt.Fprintf(&out, "export const BOARD_CELLS = %d;\n", config.BoardWidth*config.BoardHeight)
	fmt.Fprintf(&out, "export const HALFMOVE_DRAW_PLIES = %d;\n", config.HalfmoveDrawPlies)
	fmt.Fprintf(&out, "export const REPETITION_LIMIT = %d;\n", config.RepetitionLimit)
	fmt.Fprintf(&out, "export const BOARD_ALPHABET = %q;\n\n", config.BoardAlphabet)

	out.WriteString("export const START_BOARD = [\n")
	for row := 0; row < config.BoardHeight; row++ {
		out.WriteString(" ")
		for col := 0; col < config.BoardWidth; col++ {
			fmt.Fprintf(&out, " %d,", config.StartBoard[row*config.BoardWidth+col])
		}
		out.WriteString("\n")
	}
	out.WriteString("] as const;\n\n")

	writeList := func(name string, values []string) {
		fmt.Fprintf(&out, "export const %s = [\n", name)
		for _, value := range values {
			fmt.Fprintf(&out, "  %q,\n", value)
		}
		out.WriteString("] as const;\n")
	}
	writeList("STEP_KINDS", config.StepKinds)
	out.WriteString("export type StepKind = (typeof STEP_KINDS)[number];\n\n")
	writeList("MATE_REASONS", config.MateReasons)
	out.WriteString("export type MateReason = (typeof MATE_REASONS)[number];\n\n")
	writeList("DRAW_REASONS", config.DrawReasons)
	out.WriteString("export type DrawReason = (typeof DRAW_REASONS)[number];\n")
	return out.Bytes()
}

func writeFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
