package chat.ola.vn.w;

import java.util.List;

/* JADX INFO: loaded from: classes.dex */
class bk {
    public String A;
    public String B;
    public String C;
    public String D;
    public String[] E;
    public String[] F;
    public String[] G;
    public String H;
    public String I;
    public String J;
    public String K;
    public String L;
    public String M;
    public String N;
    public Long O;
    public Byte P;
    public long Q;
    public long R;
    public long S;
    public long[] T;
    public long U;
    public long V;
    public long W;
    public int X;
    public int Y;
    public int Z;
    public chat.ola.vn.entity.aa[] a;
    public int aa;
    public short ab;
    public short ac;
    public short ad;
    public short ae;
    public short af;
    public short ag;
    public short aj;
    public short ak;
    public short al;
    public byte[] am;
    public byte[] an;
    public byte[] ao;
    public byte[] ap;
    public byte aq;
    public byte as;
    public byte at;
    public byte au;
    public byte av;
    public boolean aw;
    public String c;
    public String d;
    public String e;
    public String f;
    public String g;
    public String h;
    public String i;
    public String j;
    public String k;
    public String l;
    public String m;
    public String n;
    public String o;
    public String p;
    public String q;
    public String r;
    public String s;
    public String[] t;
    public String u;
    public String v;
    public String w;
    public String x;
    public String y;
    public String z;
    public List<chat.ola.vn.message.f> b = null;
    public short ah = 0;
    public short ai = 0;
    public byte ar = -1;
    public boolean ax = false;
    public boolean ay = false;
    public boolean az = false;
    public boolean aA = false;

    public bk(short s) {
        this.ab = s;
    }
}
