'use strict';
const {uiPrefabPath}=require('../tools/ui-prefab-paths.cjs');
// Run only against a disposable Creator build whose two leaf prefabs were edited on disk.
// This test never mutates a loaded prefab or component style.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {serve,launch,boot,plot,tap,observe,build}=require('./browser-support.cjs');
const source=process.env.COCOS_UI_SOURCE;
assert.ok(source,'COCOS_UI_SOURCE must point to the disposable project assets directory');
const out=path.resolve(process.env.COCOS_UI_SOURCE_OUT||'artifacts/prefab-split/ui-source-edit');
function sourceLabel(file,name){const graph=JSON.parse(fs.readFileSync(path.join(source,uiPrefabPath(file))));const label=graph.find(c=>c.__type__==='cc.Label'&&graph[c.node?.__id__]?._name===name);assert.ok(label,`${file}/${name}`);return {font:label._fontSize,color:[label._color.r,label._color.g,label._color.b]};}
async function herd(page){return page.evaluate(()=>{const a=testApp,cc=testCc,v=a.panels.card.getComponentInChildren('LivestockBodyView'),u=a.width/cc.view.getFrameSize().width;return {root:v.node.uuid,unit:u,slots:v.node.getComponentsInChildren('HerdSlotView').map(s=>({uuid:s.node.uuid,linked:!!s.node.prefab?.asset,font:s.number.fontSize,color:[s.status.color.r,s.status.color.g,s.status.color.b],portraits:s.portrait.getComponentsInChildren(cc.Sprite).filter(x=>x.node.activeInHierarchy&&x.spriteFrame).length}))};});}
async function seeds(page){return page.evaluate(()=>{const cc=testCc,v=testApp.footer.node.getComponent('SeedPickerView');return {tiles:v.scroll.content.children.filter(n=>n.getComponent('SeedTileView')).map(n=>{const s=n.getComponent('SeedTileView');return {linked:!!n.prefab?.asset,font:s.cost.fontSize,color:[s.cost.color.r,s.cost.color.g,s.cost.color.b],visibleArt:s.seed.node.activeInHierarchy&&!!s.seed.spriteFrame};})};});}
function checkHerd(s){assert.equal(s.slots.length,5);assert.ok(s.slots.every(x=>x.linked));assert.ok(s.slots[0].portraits>0,'The modified leaf is used beside a visibly rendered resident');for(const slot of s.slots){assert.equal(slot.font,Math.ceil(13*s.unit));assert.deepEqual(slot.color,[69,126,199]);}}
function checkSeeds(s){assert.equal(s.tiles.length,8);for(const tile of s.tiles){assert.ok(tile.linked&&tile.visibleArt,'Each edited seed leaf renders actual catalog art');assert.equal(tile.font,28);assert.deepEqual(tile.color,[44,99,155]);}}
(async()=>{fs.mkdirSync(out,{recursive:true});const report={buildPath:build,sourceAssets:path.resolve(source),passed:false,cleanup:{serverClosed:false,browserClosed:false},states:[]};const save=()=>fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2)+'\n');let server,browser,context;
 try{report.source={herdNumber:sourceLabel('HerdSlot','SlotNumber'),herdStatus:sourceLabel('HerdSlot','SlotStatus'),seedCost:sourceLabel('SeedTile','Cost')};assert.equal(report.source.herdNumber.font,13);assert.deepEqual(report.source.herdStatus.color,[69,126,199]);assert.deepEqual(report.source.seedCost,{font:28,color:[44,99,155]});
 server=await serve();browser=await launch();context=await browser.newContext({viewport:{width:393,height:585},hasTouch:true,isMobile:true});const page=await context.newPage(),observed=observe(page);await boot(page,server.url);await page.evaluate(()=>{testApp.game.dismissGuide();testApp.close();testApp.map.focusBuilding('pen:12');});await plot(page,12,true);await tap(page,'herd-manage',true);
 const first=await herd(page);checkHerd(first);report.states.push({name:'herd-source-edit-393',...first});await page.screenshot({path:path.join(out,'herd-source-edit-393.png')});
 await page.evaluate(()=>testApp.panels.render());await page.setViewportSize({width:568,height:320});await page.waitForFunction(()=>testApp.panels.frameWidth===568);const rotated=await herd(page);checkHerd(rotated);assert.equal(rotated.root,first.root);assert.deepEqual(rotated.slots.map(x=>x.uuid),first.slots.map(x=>x.uuid));report.states.push({name:'herd-source-edit-resized',...rotated});
 const id=await page.evaluate(()=>{testApp.close();testApp.focusHome();return testApp.game.state.plots.find(p=>p.group==='crop'&&p.unlocked&&!p.crop).id;});await plot(page,id,true);const seed=await seeds(page);checkSeeds(seed);report.states.push({name:'seed-source-edit-568',...seed});await page.screenshot({path:path.join(out,'seed-source-edit-568.png')});
 await page.setViewportSize({width:393,height:585});await page.waitForFunction(()=>testCc.view.getFrameSize().width===393);await page.waitForTimeout(80);const resized=await seeds(page);checkSeeds(resized);report.states.push({name:'seed-source-edit-resized',...resized});assert.deepEqual(observed.errors,[]);report.errors=observed.errors;report.passed=true;console.log('Actual edited HerdSlot and SeedTile files survive Creator import, nested instances, refresh and resize PASS');
 }catch(error){report.error=String(error);report.stack=error.stack;process.exitCode=1;console.error(error.stack);}finally{if(context)await context.close();if(server){await server.close();report.cleanup.serverClosed=true;}if(browser){await browser.close();report.cleanup.browserClosed=true;}save();}
})().catch(error=>{console.error(error);process.exitCode=1;});
