/** CSS-pixel sizes for the warehouse in the factory frame; width, split and padding follow FACTORY_LAYOUT. */
export const INVENTORY_LAYOUT = {
  width: 560,
  splitWidth: 620,
  splitMinWidth: 560,
  splitMaxHeight: 500,
  height: 516,
  screenMargin: 24,
  padding: 18,
  buttonInset: 12,
  shortHeight: 420,
  summaryTop: 62,
  tabsTop: 92,
  tabHeight: 36,
  gridTop: 114,
  footerHeight: 104,
  shortFooterHeight: 80,
  footerBottom: 30,
  hintOffset: 36,
  buttonHeight: 44,
  preferredCellWidth: 76,
  minColumns: 3,
  maxColumns: 8,
  rowHeight: 96,
  shortRowHeight: 88,
} as const;
