export const API_PATH = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    refresh: '/auth/refresh',
    changePassword: '/auth/change-password',
    logout: '/auth/logout',
  },
  rooms: {
    browse: '/rooms',
    detail: (id: string) => `/rooms/${id}`,
    join: (id: string) => `/rooms/${id}/join`,
    members: (id: string) => `/rooms/${id}/members`,
    messages: (id: string) => `/rooms/${id}/messages`,
    message: (id: string, messageId: string) => `/rooms/${id}/messages/${messageId}`,
  },
  adminRooms: {
    base: '/admin/rooms',
    detail: (id: string) => `/admin/rooms/${id}`,
  },
  user: {
    me: '/user/me',
    search: '/user/search',
    upload: '/user/upload',
    detail: (id: string) => `/user/${id}`,
    kiss: (id: string) => `/user/${id}/kiss`,
    follow: (id: string) => `/user/${id}/follow`,
    followers: (id: string) => `/user/${id}/followers`,
    following: (id: string) => `/user/${id}/following`,
    myVisitors: '/user/me/visitors',
  },
  relationships: {
    request: '/relationships/request',
    respond: (id: string) => `/relationships/${id}/respond`,
    cancel: (id: string) => `/relationships/${id}/cancel`,
    unfriend: (id: string) => `/relationships/${id}/unfriend`,
    block: '/relationships/block',
    unblock: (id: string) => `/relationships/${id}/unblock`,
    pending: '/relationships/pending',
    sent: '/relationships/sent',
    friends: '/relationships/friends',
    blocked: '/relationships/blocked',
  },
  me: {
    base: '/me',
    mine: '/me/mine',
    liked: '/me/liked',
    users: (userId: string) => `/me/users/${userId}`,
    detail: (id: string) => `/me/${id}`,
    images: '/me/images',
    pin: (id: string) => `/me/${id}/pin`,
    react: (id: string) => `/me/${id}/react`,
    likers: (id: string) => `/me/${id}/likers`,
    comments: (id: string) => `/me/${id}/comments`,
    comment: (id: string, commentId: string) => `/me/${id}/comments/${commentId}`,
  },
  conversations: {
    base: '/conversations',
    directCheck: '/conversations/direct/check',
    direct: '/conversations/direct',
    group: '/conversations/group',
    detail: (id: string) => `/conversations/${id}`,
    read: (id: string) => `/conversations/${id}/read`,
    hide: (id: string) => `/conversations/${id}/hide`,
    unhide: (id: string) => `/conversations/${id}/unhide`,
    mute: (id: string) => `/conversations/${id}/mute`,
    unmute: (id: string) => `/conversations/${id}/unmute`,
    typing: '/conversations/typing',
  },
  vip: {
    store: '/vip/store',
    storePrivacy: '/vip/store/privacy',
    iconCatalog: '/vip/icons/catalog',
    buy: '/vip/buy',
    packages: '/vip/packages',
    buyPackage: (id: string) => `/vip/packages/${id}/buy`,
    iconUse: (id: string) => `/vip/icons/${id}/use`,
    iconLock: (id: string) => `/vip/icons/${id}/lock`,
    iconUnlock: (id: string) => `/vip/icons/${id}/unlock`,
    iconDelete: (id: string) => `/vip/icons/${id}`,
  },
  egg: {
    packs: '/egg/packs',
    draw: (id: string) => `/egg/packs/${id}/draws`,
    draws: '/egg/draws',
  },
  marriage: {
    status: '/marriage',
    divorce: '/marriage/divorce',
    proposals: '/marriage/proposals',
    proposal: (id: string) => `/marriage/proposals/${id}`,
    proposalAccept: (id: string) => `/marriage/proposals/${id}/accept`,
    proposalReject: (id: string) => `/marriage/proposals/${id}/reject`,
    diary: '/marriage/diary',
    diaryDetail: (id: string) => `/marriage/diary/${id}`,
  },
  messages: {
    base: '/messages',
    direct: '/messages/direct',
    images: '/messages/images',
    audio: '/messages/audio',
    byConversation: (conversationId: string) => `/messages/${conversationId}`,
    detail: (conversationId: string, messageId: string) =>
      `/messages/${conversationId}/${messageId}`,
    reactions: (conversationId: string, messageId: string) =>
      `/messages/${conversationId}/${messageId}/reactions`,
  },
} as const;
