export const API_PATH = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    refresh: '/auth/refresh',
    changePassword: '/auth/change-password',
    logout: '/auth/logout',
  },
  rooms: {
    browse: '/rooms',
    detail: (id: string) => `/rooms/${id}`,
    join: (id: string) => `/rooms/${id}/join`,
    members: (id: string) => `/rooms/${id}/members`,
    messages: (id: string) => `/rooms/${id}/messages`,
    message: (id: string, messageId: string) => `/rooms/${id}/messages/${messageId}`,
  },
  adminRooms: {
    base: '/admin/rooms',
    detail: (id: string) => `/admin/rooms/${id}`,
  },
  user: {
    me: '/user/me',
    upload: '/user/upload',
    detail: (id: string) => `/user/${id}`,
    kiss: (id: string) => `/user/${id}/kiss`,
    follow: (id: string) => `/user/${id}/follow`,
    followers: (id: string) => `/user/${id}/followers`,
    following: (id: string) => `/user/${id}/following`,
  },
  relationships: {
    request: '/relationships/request',
    respond: (id: string) => `/relationships/${id}/respond`,
    cancel: (id: string) => `/relationships/${id}/cancel`,
    unfriend: (id: string) => `/relationships/${id}/unfriend`,
    block: '/relationships/block',
    unblock: (id: string) => `/relationships/${id}/unblock`,
    pending: '/relationships/pending',
    sent: '/relationships/sent',
    friends: '/relationships/friends',
    blocked: '/relationships/blocked',
  },
  me: {
    base: '/me',
    mine: '/me/mine',
    users: (userId: string) => `/me/users/${userId}`,
    detail: (id: string) => `/me/${id}`,
    images: '/me/images',
    react: (id: string) => `/me/${id}/react`,
    likers: (id: string) => `/me/${id}/likers`,
    comments: (id: string) => `/me/${id}/comments`,
    comment: (id: string, commentId: string) => `/me/${id}/comments/${commentId}`,
  },
} as const;
