export const wheelAssets = {
  background: require('@assets/games/spin-wheel/background.webp'),
  titleBanner: require('@assets/games/spin-wheel/title-banner.webp'),
  closeButton: require('@assets/games/spin-wheel/close-button.webp'),
  kenBar: require('@assets/games/spin-wheel/ken-bar.webp'),
  plusFrame: require('@assets/games/spin-wheel/plus-frame.webp'),
  plusIcon: require('@assets/games/spin-wheel/plus-icon.webp'),
  wheelCenter: require('@assets/games/spin-wheel/wheel-center.webp'),
  wheelLogo: require('@assets/games/spin-wheel/logo.webp'),
  wheelOuterRing: require('@assets/games/spin-wheel/wheel-outer-ring.webp'),
  pointer: require('@assets/games/spin-wheel/pointer.webp'),
  spinCoin: require('@assets/games/spin-wheel/coin.webp'),
  rewardVipDays: require('@assets/games/spin-wheel/reward-vip-days.webp'),
  rewardKenRandom: require('@assets/games/spin-wheel/reward-ken-random.webp'),
  rewardVipRandom: require('@assets/games/spin-wheel/reward-vip-random.webp'),
  rewardMiss: require('@assets/games/spin-wheel/reward-miss.webp'),
  spinButton: require('@assets/games/spin-wheel/spin-button.webp'),
  spinCountNote: require('@assets/games/spin-wheel/spin-count-note.webp'),
  bottomButtonFrame: require('@assets/games/spin-wheel/bottom-buttons-frame.webp'),
  soundOn: require('@assets/games/spin-wheel/sound-on.webp'),
  soundOff: require('@assets/games/spin-wheel/sound-off.webp'),
  historyIcon: require('@assets/games/spin-wheel/history-icon.webp'),
  resultPopupFrame: require('@assets/games/spin-wheel/result-popup-frame.webp'),
  resultCloseFrame: require('@assets/games/spin-wheel/result-close-frame.webp'),
  resultCloseMark: require('@assets/games/spin-wheel/result-close-mark.webp'),
  coin: require('@assets/icons/apps/ken.png'),
} as const;

export const wheelHistoryAssets = {
  frame: require('@assets/games/spin-wheel/history/frame.png'),
  headerBanner: require('@assets/games/spin-wheel/history/header-banner.png'),
  closeButton: require('@assets/games/spin-wheel/history/close-button.png'),
  closeMark: require('@assets/games/spin-wheel/history/close-mark.png'),
  tabActive: require('@assets/games/spin-wheel/history/tab-active.png'),
  tabInactive: require('@assets/games/spin-wheel/history/tab-inactive.png'),
  pageButton: require('@assets/games/spin-wheel/history/page-button.png'),
  pagePrev: require('@assets/games/spin-wheel/history/page-prev.png'),
  pageNext: require('@assets/games/spin-wheel/history/page-next.png'),
} as const;
