// Code generated by server/cmd/xiangqigen; DO NOT EDIT.

export const GAME_ID = "xiangqi";
export const TURN_SECONDS = 60;
export const BOARD_WIDTH = 9;
export const BOARD_HEIGHT = 10;
export const BOARD_CELLS = 90;
export const HALFMOVE_DRAW_PLIES = 120;
export const REPETITION_LIMIT = 3;
export const BOARD_ALPHABET = ".KAEHRCPkaehrcp";

export const START_BOARD = [
  5, 4, 3, 2, 1, 2, 3, 4, 5,
  0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 6, 0, 0, 0, 0, 0, 6, 0,
  7, 0, 7, 0, 7, 0, 7, 0, 7,
  0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0,
  14, 0, 14, 0, 14, 0, 14, 0, 14,
  0, 13, 0, 0, 0, 0, 0, 13, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0,
  12, 11, 10, 9, 8, 9, 10, 11, 12,
] as const;

export const STEP_KINDS = [
  "move",
  "capture",
  "check",
  "mate",
  "draw",
] as const;
export type StepKind = (typeof STEP_KINDS)[number];

export const MATE_REASONS = [
  "checkmate",
  "stalemate",
  "perpetual",
] as const;
export type MateReason = (typeof MATE_REASONS)[number];

export const DRAW_REASONS = [
  "repetition",
  "halfmove",
] as const;
export type DrawReason = (typeof DRAW_REASONS)[number];
