import type { ImageSourcePropType } from 'react-native';

export const EMOJI_IMAGES: ImageSourcePropType[] = [
  require('@assets/icons/emoji/01_smiley_colon_dash_parenclose.png'),
  require('@assets/icons/emoji/02_smiley_colon_dash_P.png'),
  require('@assets/icons/emoji/03_smiley_gt_colon_D_lt.png'),
  require('@assets/icons/emoji/04_smiley_colon_parenclose_parenclose.png'),
  require('@assets/icons/emoji/05_smiley_colon_quote_gt.png'),
  require('@assets/icons/emoji/06_smiley_B_dash_parenclose.png'),
  require('@assets/icons/emoji/07_smiley_colon_dash_X.png'),
  require('@assets/icons/emoji/08_smiley_colon_dash_star.png'),
  require('@assets/icons/emoji/09_smiley_colon_dash_bar.png'),
  require('@assets/icons/emoji/10_smiley_colon_dash_D.png'),
  require('@assets/icons/emoji/11_smiley_semicolon_dash_parenclose.png'),
  require('@assets/icons/emoji/12_smiley_I_dash_parenclose.png'),
  require('@assets/icons/emoji/13_smiley_parenopen_colon_bar.png'),
  require('@assets/icons/emoji/14_smiley_colon_dash_slash.png'),
  require('@assets/icons/emoji/15_smiley_colon_dash_lt.png'),
  require('@assets/icons/emoji/16_smiley_colon_dash_amp.png'),
  require('@assets/icons/emoji/17_smiley_colon_dash_parenopen.png'),
  require('@assets/icons/emoji/18_smiley_colon_dash_B.png'),
  require('@assets/icons/emoji/19_smiley_colon_dash_O.png'),
  require('@assets/icons/emoji/20_smiley_colon_dash_h.png'),
  require('@assets/icons/emoji/21_smiley_colon_dash_S.png'),
  require('@assets/icons/emoji/22_smiley_colon_dash_question.png'),
  require('@assets/icons/emoji/23_smiley_colon_parenopen_parenopen.png'),
  require('@assets/icons/emoji/24_smiley_eq_parenopen_parenopen.png'),
  require('@assets/icons/emoji/25_smiley_eq_semicolon.png'),
  require('@assets/icons/emoji/26_smiley_colon_dash_W.png'),
  require('@assets/icons/emoji/27_smiley_X_dash_parenopen.png'),
  require('@assets/icons/emoji/28_smiley_gt_colon_parenclose.png'),
  require('@assets/icons/emoji/29_smiley_parenopen_y_parenclose.png'),
  require('@assets/icons/emoji/30_smiley_parenopen_n_parenclose.png'),
  require('@assets/icons/emoji/31_poop.png'),
];
