// Command wargodgen exports server-authoritative War God constants and parity fixtures.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	wargod "ola-chat-server/internal/game/games/war-god"
)

func main() {
	constantsPath := flag.String("constants", "", "output path for generated TypeScript constants")
	parityPath := flag.String("parity", "", "output path for the JSON parity fixture")
	flag.Parse()
	if *constantsPath == "" || *parityPath == "" {
		fmt.Fprintln(os.Stderr, "both -constants and -parity are required")
		os.Exit(2)
	}

	if err := writeFile(*constantsPath, renderConstants(wargod.ExportClientConfig())); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fixture, err := json.MarshalIndent(wargod.ExportParityFixture(), "", "  ")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fixture = append(fixture, '\n')
	if err := writeFile(*parityPath, fixture); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func renderConstants(config wargod.ClientConfig) []byte {
	var out bytes.Buffer
	out.WriteString("// Code generated by server/cmd/wargodgen; DO NOT EDIT.\n\n")
	out.WriteString("export const TILE_ORDER = [\n")
	for _, tile := range config.TileOrder {
		fmt.Fprintf(&out, "  %q,\n", tile)
	}
	out.WriteString("] as const;\n\n")
	out.WriteString("export type TileType = (typeof TILE_ORDER)[number];\n")
	baseTypes := make([]string, config.BaseTileCount)
	for i, tile := range config.TileOrder[:config.BaseTileCount] {
		baseTypes[i] = fmt.Sprintf("%q", tile)
	}
	fmt.Fprintf(&out, "export type BaseTileType = %s;\n\n", strings.Join(baseTypes, " | "))

	writeInt := func(name string, value int) {
		fmt.Fprintf(&out, "export const %s = %d;\n", name, value)
	}
	writeFloat := func(name string, value float64) {
		fmt.Fprintf(&out, "export const %s = %g;\n", name, value)
	}
	writeInt("GRID", config.Grid)
	out.WriteString("export const CELLS = GRID * GRID;\n")
	writeInt("BASE_TILE_COUNT", config.BaseTileCount)
	writeInt("SPECIAL_SWORD_ONE_IN", config.SpecialSwordOneIn)
	writeInt("SPECIAL_HEART_ONE_IN", config.SpecialHeartOneIn)
	out.WriteString("export const SPECIAL_SWORD_CHANCE = 1 / SPECIAL_SWORD_ONE_IN;\n")
	out.WriteString("export const SPECIAL_HEART_CHANCE = 1 / SPECIAL_HEART_ONE_IN;\n\n")

	writeInt("MAX_HP", config.MaxHP)
	writeInt("MAX_MP", config.MaxMP)
	writeInt("MAX_FURY", config.MaxFury)
	writeFloat("FURY_DAMAGE_MULTIPLIER", config.FuryDamageMultiplier)
	writeInt("MAX_ARMOR", config.MaxArmor)
	writeInt("ULT_COST", config.UltCost)
	writeInt("LIGHTNING_GOD_DAMAGE", config.LightningGodDamage)
	writeInt("CASCADE_BONUS_PERCENT_PER_LEVEL", config.CascadeBonusPercentPerLevel)
	writeInt("MAX_CASCADE_LEVEL", config.MaximumCascadeLevel)
	writeInt("DMG_SWORD", config.DamageSword)
	writeInt("HEAL_HEART", config.HealHeart)
	writeInt("MP_WATER", config.ManaWater)
	writeInt("ARMOR_SHIELD", config.ArmorShield)
	writeInt("FURY_PEACH", config.FuryPeach)
	writeInt("FIRE_SWORD_DMG", config.FireSwordDamage)
	writeInt("GREATER_HEART_HEAL", config.GreaterHeartHeal)
	writeInt("ARMOR_DECAY", config.ArmorDecay)
	writeInt("REFLECT_THRESHOLD", config.ReflectThreshold)
	writeInt("REFLECT_DAMAGE", config.ReflectDamage)
	return out.Bytes()
}

func writeFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
