// Code generated by server/cmd/wargodgen; DO NOT EDIT.

export const TILE_ORDER = [
  "sword",
  "peach",
  "heart",
  "water",
  "shield",
  "lightning",
  "fireSword",
  "greaterHeart",
] as const;

export type TileType = (typeof TILE_ORDER)[number];
export type BaseTileType = "sword" | "peach" | "heart" | "water" | "shield" | "lightning";

export const GRID = 8;
export const CELLS = GRID * GRID;
export const BASE_TILE_COUNT = 6;
export const SPECIAL_SWORD_ONE_IN = 13;
export const SPECIAL_HEART_ONE_IN = 10;
export const SPECIAL_SWORD_CHANCE = 1 / SPECIAL_SWORD_ONE_IN;
export const SPECIAL_HEART_CHANCE = 1 / SPECIAL_HEART_ONE_IN;

export const MAX_HP = 200;
export const MAX_MP = 100;
export const MAX_FURY = 100;
export const MAX_ARMOR = 30;
export const ULT_COST = 100;
export const LIGHTNING_GOD_DAMAGE = 20;
export const CASCADE_BONUS_PERCENT_PER_LEVEL = 10;
export const MAX_CASCADE_LEVEL = 3;
export const DMG_SWORD = 7;
export const HEAL_HEART = 5;
export const MP_WATER = 7;
export const ARMOR_SHIELD = 5;
export const FURY_PEACH = 10;
export const FIRE_SWORD_DMG = 12;
export const GREATER_HEART_HEAL = 10;
export const ARMOR_DECAY = 2;
export const REFLECT_THRESHOLD = 20;
export const REFLECT_DAMAGE = 2;
